spring.datasource.url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 8708biv
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: 8 999 777-44-33
blog.email: mail@mail.ru
blog.copyright: Михал Палыч
blog.copyrightFrom: 2020