spring.datasource.url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql: false
spring.main.allow-bean-definition-overriding: true


blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: 8 999 777-44-33
blog.email: ibogino@yandex.ru
blog.copyright: Богино Илья
blog.copyrightFrom: 2020
blog.upload.folder: upload/
blog.captchaLifeTimeInHours: 1

